### ISSUE TITLE
 UnicodeDecodeError

### ISSUE THREAD

**Issue by valenc3x** [orakaro/rainbowstream#236]
OS: windows 10 Pro
Python:  3.6.0 Anaconda
- - -
$  pip install rainbowstream
Collecting rainbowstream
  Using cached rainbowstream-1.3.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\avathar\AppData\Local\Temp\pip-build-jgzg70k4\rainbowstream\setup.py", line 44, in <module>
        long_description=open("./README.rst", "r").read(),
      File "C:\Users\avathar\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2868: character maps to <undefined>

**Comment by erikcox** [comment]
I am getting the exact same error on Windows 10. My final line has a little more info on it:

` UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2868: character maps to <undefined>`
