### ISSUE TITLE
Rainbow stream does not run

### ISSUE THREAD

**Issue by zakiaziz** [orakaro/rainbowstream#239]
I'm on OSX and I've installed by running `sudo pip install rainbowstream`. After installation when trying to run the program my terminal outputs this:
```
$ rainbowstream
Traceback (most recent call last):
  File "/usr/local/bin/rainbowstream", line 9, in <module>
    load_entry_point('rainbowstream==1.3.7', 'console_scripts', 'rainbowstream')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/rainbowstream/rainbow.py", line 29, in <module>
    from .interactive import *
  File "/usr/local/lib/python2.7/site-packages/rainbowstream/interactive.py", line 1, in <module>
    import readline
ImportError: dlopen(/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/readline.so, 2): Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/readline.so
  Reason: image not found
```
 Any idea what I'm missing?

**Comment by rodrigomaia17** [comment]
+1

**Comment by davidseibert** [comment]
I have this same issue on macOS 10.13. It was working when I first installed it, but not now. I remember installing a lot of C libraries at one point and thought "I hope this doesn't mess anything up", and here I am. I'll try to figure it out.
