### ISSUE TITLE
Installation fails (both ways) on windows

### ISSUE THREAD

**Issue by surajsharma** [orakaro/rainbowstream#246]
output of `pip install rainbowstream` on my Windows 10 pc with python 3.5.2
```
Collecting rainbowstream
  Using cached rainbowstream-1.3.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SURAJ~1.SHA\AppData\Local\Temp\pip-build-zvgiyf51\rainbowstream\setup.py", line 44, in <module>
        long_description=open("./README.rst", "r").read(),
      File "c:\users\suraj.sharma\venv\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2868: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\SURAJ~1.SHA\AppData\Local\Temp\pip-build-zvgiyf51\rainbowstream\
```

**Comment by LoZeno** [comment]
I'm having the exact same issue.
Python 3.6.4
Windows 10
`❯ pip install rainbowstream
Collecting rainbowstream
  Using cached rainbowstream-1.3.7.tar.gz
    Complete output from command python setup.py egg_info:
    'cp' is not recognized as an internal or external command,
    operable program or batch file.
    'chmod' is not recognized as an internal or external command,
    operable program or batch file.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\gfx0\AppData\Local\Temp\pip-build-x2o57nor\rainbowstream\setup.py", line 44, in <module>
        long_description=open("./README.rst", "r").read(),
      File "c:\python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2868: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\gfx0\AppData\Local\Temp\pip-build-x2o57nor\rainbowstream\`

Same output when I install using virtualenv

**Comment by ptytb** [comment]
**setup.py** must not use OS dependent commands, the correct way is using
`from shutil import chown, copy, copyfile`

**setup.py** must compile .so libraries, the app should not do that at runtime like this does.

Anyways, rainbowstream uses VT100 control sequences, so it wont work on windows terminals.

But, I got rainbowstream work under Cygwin:

From Windows (not Cygwin): keep package installation dir `pip install rainbowstream --no-clean`
Look up through a command's output for C:\...\AppData\Local\Temp\...\rainbowstream package location.

From Cygwin terminal
```
/bin/pip3 install virtualenv
/bin/python3 -m virtualenv env
source env/bin/activate
/bin/pip3 install /cygdrive/c/.../AppData/Local/Temp.../rainbowstream
```

For Cygwin, install Links Browser package, then run rainbowstream, it will request your credentials, you'll remember authorization PIN and enter it back to rainbowstream.
