### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by guido4000** [orakaro/rainbowstream#25]
OSX 10.9.4.

```
Successfully installed rainbowstream python-dateutil requests six
Cleaning up...
```

@main ➜  ~  rainbowstream

```
Traceback (most recent call last):
  File "/usr/local/bin/rainbowstream", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: Pillow
```

**Comment by Thomasxiaof** [comment]
D:\Python27\pip-1.5.6>testdroid
Traceback (most recent call last):
  File "D:\Python27\Scripts\testdroid-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "D:\Python27\lib\site-packages\pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "D:\Python27\lib\site-packages\pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "D:\Python27\lib\site-packages\pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: pillow


Hi All,I do not know how to reslove it,please help?Thanks
