### ISSUE TITLE
Fedora 28 x64 Not working

### ISSUE THREAD

**Issue by xzj8b3** [orakaro/rainbowstream#275]
Traceback (most recent call last):
  File "/usr/bin/rainbowstream", line 7, in <module>
    from rainbowstream.rainbow import fly
  File "/usr/lib/python2.7/site-packages/rainbowstream/rainbow.py", line 25, in <module>
    from .draw import *
  File "/usr/lib/python2.7/site-packages/rainbowstream/draw.py", line 15, in <module>
    from .c_image import *
  File "/usr/lib/python2.7/site-packages/rainbowstream/c_image.py", line 25, in <module>
    rgb2short = call_c()
  File "/usr/lib/python2.7/site-packages/rainbowstream/c_image.py", line 21, in call_c
    image_c = ctypes.cdll.LoadLibrary(library)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 439, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 361, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /root/.image.so: cannot open shared object file: No such file or directory

**Comment by nstr10** [comment]
First off, it looks like you're running this as root. That's probably not a great idea for any project.

On line 20 of c_image.py, change `os.system(build + " >/dev/null 2>&1")` to just `os.system(build)` and you should then see an error from the attempt to build the shared object, which seems like the only logical cause of this error.

One solution might be to capture the output of the call to `os.sytem()` and, if the file continues not to exist after the attempt to create it, exit and print that output.
