### ISSUE TITLE
Rate exceeded?

### ISSUE THREAD

**Issue by cavaughankirov** [orakaro/rainbowstream#282]
Last week the new rainbowstream was working great. Awesome work!!! However, today I'm getting errors. At the very end I removed a lot of text which I feared might have some credential information.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/curtis/venv/lib/python3.7/site-packages/twitter/api.py", line 341, in _handle_response
    handle = urllib_request.urlopen(req, **kwargs)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/curtis/venv/lib/python3.7/site-packages/rainbowstream/rainbow.py", line 2173, in stream
    poll()
  File "/home/curtis/venv/lib/python3.7/site-packages/rainbowstream/rainbow.py", line 343, in poll
    result = t.statuses.home_timeline(**kwargs)
  File "/home/curtis/venv/lib/python3.7/site-packages/twitter/api.py", line 334, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "/home/curtis/venv/lib/python3.7/site-packages/twitter/api.py", line 367, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 429 for URL: 1.1/statuses/home_timeline.json using parameters: (....cut out this info....)
details: {'errors': [{'message': 'Rate limit exceeded', 'code': 88}]}

**Comment by A-Sm1th** [comment]
Exact same issue here!

**Comment by Setheck** [comment]
Just got this as well :(

**Comment by CuriousMarc** [comment]
I get the same thing.

**Comment by johnpiers** [comment]
Correct me if I'm wrong, the only time this happens to me is if the data (internet) connection is disrupted, even for the shortest moment during Rainbowstream's refresh (90 seconds) period. The way I see it is that once this happens Rainbowstream does not recover from the occurrence and you have to quit and restart.  I'm not sure if this is the intended and expected behaviour.

**Comment by CuriousMarc** [comment]
No, it seems to recover and there was no interruption in the connection that I know of - this is on a wired network.

**Comment by CuriousMarc** [comment]
I thought it was from me using Twitter on another platform, but it happens even when the rainbow client is the only client accessing it.

**Comment by chammaaomar** [comment]
so it happened to me just today. I tried using me, which would show my latest tweets, but using me 2 to show my two latest tweets returns `Over capacity` and then returns either 404 or 500 in the call stack... My internet connection seems perfectly stable

**Comment by johnpiers** [comment]
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/twitter/api.py", line 341, in _handle_response
    handle = urllib_request.urlopen(req, **kwargs)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/rainbowstream/rainbow.py", line 2173, in stream
    poll()
  File "/usr/lib/python3.8/site-packages/rainbowstream/rainbow.py", line 343, in poll
    result = t.statuses.home_timeline(**kwargs)
  File "/usr/lib/python3.8/site-packages/twitter/api.py", line 334, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "/usr/lib/python3.8/site-packages/twitter/api.py", line 367, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 500 for URL: 1.1/statuses/home_timeline.json using parameters: (count=5&oauth_consumer_key=Xk1DGhR1FJa4xjg7GbdogzLJw&oauth_nonce=12826825401898145403&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1587391369&oauth_token=326179322-WM7pofJ3ZS4r2k17Hyw6oHD06rSwpitqN93TNABQ&oauth_version=1.0&since_id=1252234820177948675&tweet_mode=extended&oauth_signature=UtAHueyDpxSIjkyA4gOjuyvWlP0%3D)
details: {'errors': [{'message': 'Internal error', 'code': 131}]}
home`
This just happened, about 2 minutes ago, not sure if the connection dropped for a few seconds or not, generally this is when it seems to happen.

**Comment by everdred** [comment]
This happens to me without fail when I `switch public [keyword]` but never in any other situation I've found.
