### ISSUE TITLE
Rainbowstream Won't run

### ISSUE THREAD

**Issue by johnpiers** [orakaro/rainbowstream#308]
I've tried everything and just cannot get rainbowstream to run or work. I've been using this since it got created and absolutely love this thing but am at a loss in terms of what to, if it's obvious then apologies but I don't really know where to start as regards finding the problem. I've installed it via "The Recommended Way" as opposed to the quick way that also did not work. Using python3, latest version of pip, my OS is Arch Linux. 
Thanks, Piers.

> Traceback (most recent call last):
>   File "/home/johnpiers/venv/bin/rainbowstream", line 5, in <module>
>     from rainbowstream.rainbow import fly
>   File "/home/johnpiers/venv/lib/python3.9/site-packages/rainbowstream/rainbow.py", line 25, in <module>
>     from .draw import *
>   File "/home/johnpiers/venv/lib/python3.9/site-packages/rainbowstream/draw.py", line 15, in <module>
>     from .c_image import *
>   File "/home/johnpiers/venv/lib/python3.9/site-packages/rainbowstream/c_image.py", line 5, in <module>
>     from .py3patch import *
>   File "/home/johnpiers/venv/lib/python3.9/site-packages/rainbowstream/py3patch.py", line 11, in <module>
>     unescape = HTMLParser().unescape
> AttributeError: 'HTMLParser' object has no attribute 'unescape'`

**Comment by johnpiers** [comment]
`webgp-eu commented 16 hours ago • 
Hello,
I have looked at the code and, on my computer, with Python 3.9.5, it seems to work with the following modification:
in the file py3patch.py, add at the top of the file:
import html
and replace line number 11:
unescape = HTMLParser().unescape
with
unescape = html.unescape

I have not checked if this keeps the compatibilty with previous versions of python, though.

GP

P.S. In fact, I have just noticed that there is already a pull request (#305 ) with the same solution...`

Followed these instructions and got everything to work. Many thanks.
