### ISSUE TITLE
Failed install on Python 3.9.5

### ISSUE THREAD

**Issue by bdspinoza** [orakaro/rainbowstream#310]
Tried installing Rainbowstream with pip, and the recommended way with venv, failed both times with this output:

  `Traceback (most recent call last):
 File "/home/eme/.local/bin/rainbowstream", line 5, in <module>
    from rainbowstream.rainbow import fly
  File "/home/eme/.local/lib/python3.9/site-packages/rainbowstream/rainbow.py", line 25, in <module>
    from .draw import *
 File "/home/eme/.local/lib/python3.9/site-packages/rainbowstream/draw.py", line 15, in <module>
    from .c_image import *
  File "/home/eme/.local/lib/python3.9/site-packages/rainbowstream/c_image.py", line 5, in <module>
    from .py3patch import *
  File "/home/eme/.local/lib/python3.9/site-packages/rainbowstream/py3patch.py", line 11, in <module>
    unescape = HTMLParser().unescape
AttributeError: 'HTMLParser' object has no attribute 'unescape'
`

Running Python 3.9.5 on Manjaro Linux 21.0.5

I'm really not familiar with Python so any help is appreciated :)

**Comment by GoodClover** [comment]
Same issue here, Python 3.9.0 running Raspberry Pi OS (Debian 10/buster)

**Comment by johnpiers** [comment]
I posted my problem on the 16 May (basically exactly the same problem as the folk above and by the looks of it, a shit load of other people) and although quite a few people clicked the thumbs up on my post, got absolutely zero in terms of any answers or solutions. It's really such a pity as I've pretty much been using Rainbowstream since it was authored and absolutely loved using this but it seems like the end of the road for me anyway.

**Comment by webgp-eu** [comment]
Hello,
I have looked at the code and, on my computer, with Python 3.9.5, it seems to work with the following modification:
in the file py3patch.py, add at the top of the file:
`import html`
and replace line number 11:
`unescape = HTMLParser().unescape`
with 
`unescape = html.unescape`

I have not checked if this keeps the compatibilty with previous versions of python, though.

GP

**Comment by johnpiers** [comment]
I'm at a loss for words! Followed your instructions and voilà, finally got everything working! Thank you so much.
