### ISSUE TITLE
App does not launch: `ModuleNotFoundError: No module named 'rainbowstream.consumer'`

### ISSUE THREAD

**Issue by barracuda156** [orakaro/rainbowstream#345]
```
36-125% /opt/local/bin/rainbowstream
Traceback (most recent call last):
  File "/opt/local/bin/rainbowstream", line 5, in <module>
    from rainbowstream.rainbow import fly
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rainbowstream/rainbow.py", line 28, in <module>
    from .consumer import *
ModuleNotFoundError: No module named 'rainbowstream.consumer'
```

What do I miss?

**Comment by johnpiers** [comment]
This app, I am afraid, is dead in the water. You can learn more here: https://developer.twitter.com/en/portal/product
