### ISSUE TITLE
ImportError: No module named consumer

### ISSUE THREAD

**Issue by daryltucker** [orakaro/rainbowstream#6]
```
$ rainbowstream
Traceback (most recent call last):
  File "/usr/local/bin/rainbowstream", line 9, in <module>
    load_entry_point('rainbowstream==0.2.5', 'console_scripts', 'rainbowstream')()
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 357, in load_entry_point

  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2465, in load_entry_point
    )
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2181, in load
    return s
  File "/usr/local/lib/python2.7/dist-packages/rainbowstream/rainbow.py", line 25, in <module>
    from .consumer import *
```

**Comment by ejmg** [comment]
Hi there @orakaro, I am actually very curious how this is actually handled by your app? I am trying to make my own twitter related app and I don't know how to deploy it without keeping my consumer tokens secret. Could you explain that by any chance? Thank you very much.
